In [ ]:
import matplotlib.pyplot as plt, numpy as np
import seaborn as sns
import pandas as pd
!pip install pandas
!pip install --upgrade xlrd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.6)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (2.0.1)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#!ls"/content/drive/My Drive/fp_521"
df=pd.read_excel('drive/My Drive/fp_421/suns_data.xls')
df.head()

,Rk,Unnamed: 1,Age,G,GS,MP,FG,FGA,FG%,3P,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1.0,Devin Booker,26.0,10,10.0,364,95,196,0.485,21,...,0.857,8,34,42,51,9,5,30,23,271
1,2.0,Mikal Bridges,26.0,10,10.0,359,56,95,0.589,11,...,0.867,12,37,49,27,8,11,11,22,149
2,3.0,Chris Paul,37.0,10,10.0,302,28,76,0.368,9,...,0.882,5,40,45,94,17,2,15,23,95
3,4.0,Deandre Ayton,24.0,8,8.0,206,53,93,0.570,3,...,0.765,19,43,62,12,4,5,18,31,122
4,5.0,Cameron Johnson,26.0,8,8.0,202,37,83,0.446,22,...,0.727,5,22,27,14,9,3,2,14,104

In [ ]:
team_dict = {'hawks_data': 'Hawks'
,'celtics_data' : 'Celtics'
,'wizards_data' : 'Wizards'
,'Hornets_data' : 'Hornets'
,'Bulls_data' : 'Bulls'
,'Cavaliers_data' : 'Cavaliers'
,'Mavericks_data' : 'Mavericks'
,'Nuggets_data' : 'Nuggets'
,'Pistons_data' : 'Pistons'
,'Warriors_data' : 'Warriors'
,'Rockets_data' : 'Rockets'
,'Pacers_data' : 'Pacers' 
,'Clippers_data' : 'Clippers'
,'Lakers_data' : 'Lakers'
,'Grizzlies_data' : 'Grizzlies'
,'Heat_data' : 'Heat'
,'Bucks_data' : 'Bucks'
,'Timberwolves_data' : 'Timberwolves'
,'Pelicans_data' : 'Pelicans'
,'Knicks_data' : 'Knicks'
,'Thunder_data' : 'Thunder'
,'Magic_data' : 'Magic'
,'76ers_data' : '76ers'
,'Suns_data' : 'Suns'
,'Trail_Blazers_data' : 'Blazers'
,'Kings_data' : 'Kings'
,'Spurs_data' : 'Spurs'
,'Raptors_data' : 'Raptors'
,'Jazz_data' : 'Jazz'}

In [ ]:
team_dict =  {k.lower(): v for k, v in team_dict.items()}
team_dict_len = len(team_dict)

In [ ]:
print(team_dict)

{'hawks_data': 'Hawks', 'celtics_data': 'Celtics', 'wizards_data': 'Wizards', 'hornets_data': 'Hornets', 'bulls_data': 'Bulls', 'cavaliers_data': 'Cavaliers', 'mavericks_data': 'Mavericks', 'nuggets_data': 'Nuggets', 'pistons_data': 'Pistons', 'warriors_data': 'Warriors', 'rockets_data': 'Rockets', 'pacers_data': 'Pacers', 'clippers_data': 'Clippers', 'lakers_data': 'Lakers', 'grizzlies_data': 'Grizzlies', 'heat_data': 'Heat', 'bucks_data': 'Bucks', 'timberwolves_data': 'Timberwolves', 'pelicans_data': 'Pelicans', 'knicks_data': 'Knicks', 'thunder_data': 'Thunder', 'magic_data': 'Magic', '76ers_data': '76ers', 'suns_data': 'Suns', 'trail_blazers_data': 'Blazers', 'kings_data': 'Kings', 'spurs_data': 'Spurs', 'raptors_data': 'Raptors', 'jazz_data': 'Jazz'}

In [ ]:
master_df = pd.read_excel('drive/My Drive/fp_421/nets.xls')
cols_to_check = master_df.columns
master_df['is_na'] = master_df[cols_to_check].isnull().apply(lambda x: all(x), axis=1) 
master_df = master_df[master_df['is_na']==False]
master_df['TEAM'] = 'Nets'
for key in team_dict:
    xls_name = key + '.xls'
    data = pd.read_excel('drive/My Drive/fp_421/'+xls_name)
    cols_to_check = data.columns
    data['is_na'] = data[cols_to_check].isnull().apply(lambda x: all(x), axis=1) 
    data = data[data['is_na']==False]
    data['TEAM'] = team_dict[key]
    master_df = master_df.append(data)

# New Section

In [ ]:
master_df.shape

(449, 30)

In [ ]:
master_df.head(40)

,Rk,Unnamed: 1,Age,G,GS,MP,FG,FGA,FG%,3P,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,is_na,TEAM
0,1.0,Kyrie Irving,30.0,3.0,3.0,113.0,31.0,67.0,0.463,7.0,...,8.0,11.0,17.0,4.0,3.0,7.0,10.0,82.0,False,Nets
1,2.0,Royce O'Neale,29.0,3.0,3.0,109.0,9.0,26.0,0.346,5.0,...,12.0,14.0,10.0,6.0,6.0,2.0,9.0,25.0,False,Nets
2,3.0,Kevin Durant,34.0,3.0,3.0,106.0,33.0,59.0,0.559,6.0,...,11.0,13.0,12.0,1.0,6.0,10.0,10.0,96.0,False,Nets
3,4.0,Nic Claxton,23.0,3.0,3.0,92.0,21.0,28.0,0.750,0.0,...,16.0,28.0,0.0,2.0,8.0,4.0,9.0,48.0,False,Nets
4,5.0,Ben Simmons,26.0,3.0,3.0,84.0,7.0,13.0,0.538,0.0,...,18.0,18.0,21.0,1.0,2.0,11.0,14.0,17.0,False,Nets
5,6.0,Patty Mills,34.0,3.0,0.0,53.0,9.0,19.0,0.474,8.0,...,1.0,2.0,2.0,0.0,0.0,0.0,0.0,32.0,False,Nets
6,7.0,Day'Ron Sharpe,21.0,3.0,0.0,47.0,5.0,13.0,0.385,0.0,...,11.0,18.0,2.0,2.0,3.0,1.0,12.0,13.0,False,Nets
7,8.0,Joe Harris,31.0,2.0,0.0,40.0,4.0,12.0,0.333,3.0,...,4.0,7.0,4.0,0.0,1.0,0.0,5.0,11.0,False,Nets
8,9.0,Markieff Morris,33.0,2.0,0.0,22.0,2.0,5.0,0.400,2.0,...,3.0,4.0,0.0,0.0,1.0,1.0,3.0,6.0,False,Nets
9,10.0,Edmond Sumner,27.0,2.0,0.0,22.0,2.0,5.0,0.400,0.0,...,1.0,1.0,4.0,0.0,0.0,4.0,1.0,6.0,False,Nets
10,11.0,Yuta Watanabe,28.0,2.0,0.0,15.0,0.0,2.0,0.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,False,Nets
11,12.0,Cam Thomas,21.0,1.0,0.0,13.0,1.0,4.0,0.250,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,False,Nets
12,13.0,Kessler Edwards,22.0,1.0,0.0,4.0,1.0,3.0,0.333,1.0,...,2.0,2.0,2.0,1.0,0.0,0.0,0.0,3.0,False,Nets
13,NaN,NaN,NaN,3.0,NaN,720.0,125.0,256.0,0.488,32.0,...,87.0,118.0,75.0,17.0,30.0,40.0,74.0,341.0,False,Nets
0,1.0,Dejounte Murray,26.0,3.0,3.0,117.0,23.0,50.0,0.460,5.0,...,20.0,22.0,25.0,10.0,2.0,11.0,4.0,59.0,False,Hawks
1,2.0,Trae Young,24.0,3.0,3.0,109.0,23.0,71.0,0.324,7.0,...,8.0,12.0,35.0,1.0,1.0,10.0,8.0,76.0,False,Hawks
2,3.0,John Collins,25.0,3.0,3.0,108.0,21.0,38.0,0.553,5.0,...,26.0,31.0,2.0,5.0,5.0,5.0,9.0,57.0,False,Hawks
3,4.0,De'Andre Hunter,25.0,3.0,3.0,96.0,19.0,38.0,0.500,3.0,...,11.0,14.0,6.0,2.0,0.0,2.0,9.0,44.0,False,Hawks
4,5.0,Clint Capela,28.0,3.0,3.0,81.0,11.0,17.0,0.647,0.0,...,18.0,25.0,1.0,3.0,4.0,2.0,7.0,24.0,False,Hawks
5,6.0,Onyeka Okongwu,22.0,3.0,0.0,61.0,11.0,16.0,0.688,0.0,...,11.0,17.0,1.0,1.0,2.0,3.0,12.0,26.0,False,Hawks
6,7.0,Justin Holiday,33.0,3.0,0.0,56.0,5.0,20.0,0.250,5.0,...,2.0,2.0,5.0,2.0,2.0,0.0,5.0,15.0,False,Hawks
7,8.0,Aaron Holiday,26.0,3.0,0.0,46.0,4.0,12.0,0.333,1.0,...,2.0,2.0,2.0,4.0,0.0,3.0,4.0,11.0,False,Hawks
8,9.0,Jalen Johnson,21.0,3.0,0.0,36.0,3.0,7.0,0.429,0.0,...,2.0,4.0,0.0,0.0,0.0,2.0,3.0,12.0,False,Hawks
9,10.0,AJ Griffin,19.0,1.0,0.0,6.0,3.0,4.0,0.750,2.0,...,0.0,0.0,0.0,2.0,0.0,0.0,0.0,8.0,False,Hawks
10,11.0,Trent Forrest,24.0,1.0,0.0,2.0,0.0,0.0,NaN,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,False,Hawks
11,12.0,Vit Krejci,22.0,1.0,0.0,2.0,0.0,0.0,NaN,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,False,Hawks
12,13.0,Tyrese Martin,23.0,1.0,0.0,2.0,1.0,1.0,1.000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,False,Hawks
13,NaN,NaN,NaN,3.0,NaN,720.0,124.0,274.0,0.453,28.0,...,100.0,129.0,79.0,30.0,16.0,38.0,61.0,334.0,False,Hawks
1,1.0,Jayson Tatum,24.0,4.0,4.0,149.0,45.0,81.0,0.556,12.0,...,31.0,33.0,14.0,3.0,5.0,7.0,6.0,130.0,False,Celtics
2,2.0,Jaylen Brown,26.0,4.0,4.0,145.0,38.0,81.0,0.469,9.0,...,17.0,22.0,11.0,5.0,6.0,10.0,11.0,96.0,False,Celtics
3,3.0,Marcus Smart,28.0,4.0,4.0,139.0,13.0,34.0,0.382,5.0,...,9.0,11.0,24.0,4.0,2.0,9.0,11.0,39.0,False,Celtics
4,4.0,Derrick White,28.0,4.0,4.0,111.0,15.0,33.0,0.455,8.0,...,12.0,15.0,13.0,2.0,3.0,3.0,12.0,44.0,False,Celtics
5,5.0,Grant Williams,24.0,4.0,0.0,99.0,12.0,17.0,0.706,8.0,...,15.0,17.0,6.0,1.0,4.0,2.0,12.0,38.0,False,Celtics
6,6.0,Malcolm Brogdon,30.0,4.0,0.0,92.0,18.0,43.0,0.419,4.0,...,9.0,15.0,13.0,3.0,0.0,8.0,7.0,48.0,False,Celtics
7,7.0,Al Horford,36.0,3.0,3.0,82.0,8.0,19.0,0.421,7.0,...,12.0,15.0,4.0,0.0,1.0,3.0,7.0,23.0,False,Celtics
8,8.0,Noah Vonleh,27.0,4.0,1.0,61.0,5.0,10.0,0.500,0.0,...,7.0,15.0,0.0,2.0,6.0,4.0,17.0,10.0,False,Celtics
9,9.0,Sam Hauser,25.0,4.0,0.0,34.0,6.0,11.0,0.545,6.0,...,3.0,4.0,1.0,1.0,0.0,0.0,3.0,19.0,False,Celtics
10,10.0,Blake Griffin,33.0,3.0,0.0,23.0,1.0,7.0,0.143,0.0,...,4.0,9.0,3.0,1.0,0.0,0.0,4.0,3.0,False,Celtics
11,11.0,Luke Kornet,27.0,2.0,0.0,11.0,1.0,3.0,0.333,0.0,...,2.0,4.0,0.0,0.0,0.0,1.0,1.0,3.0,False,Celtics
12,12.0,Payton Pritchard,25.0,2.0,0.0,9.0,2.0,6.0,0.333,2.0,...,1.0,1.0,2.0,0.0,0.0,0.0,1.0,6.0,False,Celtics

Checking for null values:

In [ ]:
master_df.isnull().sum()

Rk             30
Unnamed: 1     30
Age            30
G               0
GS             30
MP              0
FG              0
FGA             0
FG%            18
3P              0
3PA             0
3P%            64
2P              0
2PA             0
2P%            37
eFG%           18
FT              0
FTA             0
FT%           103
ORB             0
DRB             0
TRB             0
AST             0
STL             0
BLK             0
TOV             0
PF              0
PTS             0
is_na           0
TEAM            0
dtype: int64

In [ ]:
master_df[master_df.isna().any(axis=1)]

In [ ]:
master_df = master_df.fillna(0) #filled null with zeroes since most of the players with null values had zeroes everywhere else.
master_df.isnull().sum() #no more null values

Manipulating our dataframe:

In [ ]:
#adding in teams that made it to the final four manually since this is simpler than webscraping

In [ ]:
master_df['Final_Four']=np.where(((master_df["TEAM"] == "Warriors") | (master_df["TEAM"] == "Mavericks") | (master_df["TEAM"] == "Heat") | (master_df["TEAM"] == "Celtics")), 1, 0)
master_df.head()
master_df['Final_Four'].value_counts()

Separating our data into 2: one df with 'active players' which we defined as players that played more than 30 mins during the season.

In [ ]:
active_players = master_df[master_df['MP']>=30]
active_players

Visualizations:

In [ ]:
plt.hist(master_df['MP'])
plt.title("Distribution of Minutes Played")
plt.show()

In [ ]:
plt.hist(master_df['Age'])
plt.title("Distribution of Player Ages")
plt.show()

That's odd, why do we have players that are between 0-4? Let's take a look at this

In [ ]:
master_df[master_df['Age']<18] #looks some players have 0's as their name, maybe we concatenated the data incorrectly?

Checking for collinearity: 
We can see that there may be some collinearity concerns between features. Specifically, ORB and TRB, TRB and STL, TOV and ORB, TOV and TRB, TOV and STL, TOV and MP, MP and FGA, MP and 3P, etc.

In [ ]:
correlation_features = master_df.drop(['Player_name', 'TEAM'], axis=1)
corr = correlation_features.corr()
heatmap = sns.heatmap(corr)
plt.show()

In [ ]:
cols = df.columns
for i in team_dict_len():

SyntaxError: ignored